//users
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const SAVE_ANSWER_TO_USER = 'SAVE_ANSWER_TO_USER'
export const SAVE_QUESTION_TO_USER = 'SAVE_QUESTION_TO_USER'
//questions
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const SAVE_ANSWER_TO_QUESTION = 'SAVE_ANSWER_TO_QUESTION'
export const SAVE_QUESTION_TO_QUESTIONS = 'SAVE_QUESTION_TO_QUESTIONS'
//authedUser
export const SET_AUTHED_USER = 'SET_AUTHED_USER'